apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: production
  labels:
    app: cloudinary-next
    tier: backend
  annotations: 
    kubernetes.io/description: "Secrets for cloudinary"
type: Opaque
immutable: true                
stringData:
  CLOUDINARY_CLOUD_NAME: "dgdas7pc5"
  CLOUDINARY_API_KEY: "875779778563466"
  CLOUDINARY_API_SECRET: "J6qMDRq5NSwMWJ0TroC2OwH8jVI"
  NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: "dgdas7pc5"
  NEXT_PUBLIC_CLOUDINARY_UPLOAD_PRESET: "your_cloud_name"
  MONGODB_URI: "mongodb+srv://dbuser:clodinary123@cluster0.odibl9a.mongodb.net"
  # JWT_SECRET: "your_jwt_string"
  MONGO_USER: "dbuser"
  MONGO_PASS: "clodinary123"
