apiVersion: v1
kind: ConfigMap
metadata:
   name: backend-config
   namespace: production
   labels:
    app: cloudinary-next
    tier: backend
data:
  NODE_ENV: "production"
  PORT: "5000"
  FRONTEND_URL: "http://frontend-service:80" 