apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: production
spec:
  serviceName: "mongodb-service" 
  replicas: 3                  
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongo
        image: mongo:5.0         
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_USER
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: backend-secret
              key: MONGO_PASS
        # MONGODB ONLY NEEDS THIS MOUNT:
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db 

  # THIS IS WHERE MONGODB GETS ITS STORAGE:
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard" 
      resources:
        requests:
          storage: 5Gi
