apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: production
  labels:
    app: cloudinary-next
    tier: frontend
spec:
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  externalTrafficPolicy: Local
  selector:
    app: cloudinary-next
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30007
    
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30443